/* X&O Lab add-on: Pro Drills
   Additive only. Saves under playbooks/{playbookId}/drills and never touches live plays/formations. */
(function(){
  'use strict';
  const FW=1000,FH=600;
  const st={items:[],current:null,objects:[],moves:[],tool:'select',selected:null,drawing:null,canvas:null,ctx:null,scale:1,offX:0,offY:0,anim:false,animStart:0};
  const wait=()=>new Promise(r=>setTimeout(r,50));
  async function api(){ for(let i=0;i<80;i++){ if(window.XOLab) return window.XOLab; await wait(); } throw new Error('X&O Lab core is not ready yet.'); }
  function esc(s){return String(s||'').replace(/[<>&"]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;'}[c]));}
  function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36);}
  function toast(m,t){(window.toast||alert)(m,t||'');}
  function proGuard(A){ return async function(){ const x=await api(); if(!x.isProRole()){ if(window.openProInfo) window.openProInfo(); else toast('Pro required','err'); return; } return A.apply(this,arguments); }; }
  function col(x,pbId){return x.collection(x.db,'playbooks',pbId,'drills');}
  function ref(x,pbId,id){return x.doc(x.db,'playbooks',pbId,'drills',id);}
  function toS(x,y){const c=st.canvas;return {x:x*st.scale+st.offX+c.width/2-FW/2*st.scale,y:y*st.scale+st.offY+c.height/2-FH/2*st.scale};}
  function toF(x,y){const c=st.canvas;return {x:(x-st.offX-c.width/2+FW/2*st.scale)/st.scale,y:(y-st.offY-c.height/2+FH/2*st.scale)/st.scale};}
  function fit(){const c=st.canvas,p=18;st.scale=Math.min((c.width-p*2)/FW,(c.height-p*2)/FH);st.offX=0;st.offY=0;}
  function field(){const ctx=st.ctx,a=toS(0,0),b=toS(FW,FH),w=b.x-a.x,h=b.y-a.y;ctx.fillStyle='#1e4d18';ctx.fillRect(a.x,a.y,w,h);for(let i=0;i<10;i++){ctx.fillStyle=i%2?'#1a4516':'#234f1c';ctx.fillRect(a.x,a.y+i*h/10,w,h/10);}ctx.strokeStyle='rgba(255,255,255,.32)';for(let i=0;i<=10;i++){let y=a.y+i*h/10;ctx.beginPath();ctx.moveTo(a.x,y);ctx.lineTo(b.x,y);ctx.stroke();}ctx.strokeStyle='rgba(255,255,255,.55)';ctx.strokeRect(a.x,a.y,w,h);}
  function movePoint(o){ if(!st.anim) return o; const m=st.moves.find(x=>x.objectId===o.id); if(!m||!m.points||m.points.length<2)return o; const t=Math.min(1,(performance.now()-st.animStart)/1800); const a=m.points[0],b=m.points[m.points.length-1]; return {...o,x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t}; }
  function drawObj(raw){const o=movePoint(raw),ctx=st.ctx,s=toS(o.x,o.y);ctx.save();if(st.selected===raw){ctx.shadowColor='#fff';ctx.shadowBlur=12;} if(o.type==='cone'){ctx.fillStyle='#f97316';ctx.beginPath();ctx.moveTo(s.x,s.y-18);ctx.lineTo(s.x-14,s.y+14);ctx.lineTo(s.x+14,s.y+14);ctx.closePath();ctx.fill();} else if(o.type==='bag'){ctx.fillStyle='#8b5e34';ctx.fillRect(s.x-22,s.y-12,44,24);} else if(o.type==='ball'){ctx.fillStyle='#8b4513';ctx.beginPath();ctx.ellipse(s.x,s.y,18,11,0,0,Math.PI*2);ctx.fill();} else {ctx.fillStyle=o.color||'#f0b429';ctx.beginPath();ctx.arc(s.x,s.y,18,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#111';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#000';ctx.font='bold 11px DM Sans';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText((o.label||'P').slice(0,3),s.x,s.y);}ctx.restore();}
  function drawMove(m){if(!m.points||m.points.length<2)return;const ctx=st.ctx;ctx.strokeStyle='#41c97a';ctx.lineWidth=4;ctx.lineCap='round';ctx.beginPath();m.points.forEach((p,i)=>{const s=toS(p.x,p.y);i?ctx.lineTo(s.x,s.y):ctx.moveTo(s.x,s.y);});ctx.stroke();}
  function draw(){if(!st.canvas)return;st.ctx.clearRect(0,0,st.canvas.width,st.canvas.height);field();st.moves.forEach(drawMove);st.objects.forEach(drawObj); if(st.anim){if(performance.now()-st.animStart<1850)requestAnimationFrame(draw);else{st.anim=false;draw();}}}
  function resize(){const w=document.getElementById('drillCanvasWrap'); if(!w||!st.canvas)return;st.canvas.width=w.offsetWidth;st.canvas.height=w.offsetHeight;fit();draw();}
  function hit(f){return st.objects.find(o=>Math.hypot(o.x-f.x,o.y-f.y)<30/st.scale);}
  function ev(e){const r=st.canvas.getBoundingClientRect(),t=e.touches?e.touches[0]:e;return {x:t.clientX-r.left,y:t.clientY-r.top};}
  function bind(){st.canvas=document.getElementById('drillCanvas');st.ctx=st.canvas.getContext('2d');resize();window.addEventListener('resize',resize);const down=e=>{e.preventDefault();const s=ev(e),f=toF(s.x,s.y); if(['player','cone','bag','ball'].includes(st.tool)){const o={id:uid(),type:st.tool,label:st.tool==='player'?'P':'',x:f.x,y:f.y,color:'#f0b429'};st.objects.push(o);st.selected=o;draw();return;} if(st.tool==='move'){const h=hit(f); if(h){st.selected=h; st.drawing={objectId:h.id,points:[{x:h.x,y:h.y},f]}; st.moves=st.moves.filter(m=>m.objectId!==h.id); st.moves.push(st.drawing); draw();} return;} if(st.tool==='erase'){const h=hit(f); if(h){st.objects=st.objects.filter(o=>o!==h);st.moves=st.moves.filter(m=>m.objectId!==h.id);st.selected=null;draw();}return;} st.selected=hit(f);draw();};const move=e=>{if(!st.selected&&!st.drawing)return;e.preventDefault();const s=ev(e),f=toF(s.x,s.y); if(st.drawing){st.drawing.points=[st.drawing.points[0],f];draw();return;} if(st.selected){st.selected.x=Math.max(0,Math.min(FW,f.x));st.selected.y=Math.max(0,Math.min(FH,f.y));draw();}};const up=()=>{st.drawing=null;};['mousedown','touchstart'].forEach(n=>st.canvas.addEventListener(n,down,{passive:false}));['mousemove','touchmove'].forEach(n=>st.canvas.addEventListener(n,move,{passive:false}));['mouseup','mouseleave','touchend'].forEach(n=>st.canvas.addEventListener(n,up));}
  async function load(){const x=await api(),pb=x.currentPlaybook(); if(!pb)return; const snap=await x.getDocs(x.query(col(x,pb.id),x.orderBy('updatedAt'))); st.items=snap.docs.map(d=>({id:d.id,...d.data()})).reverse(); renderList();}
  function renderList(){const el=document.getElementById('drillsList'); if(!el)return; if(!st.items.length){el.innerHTML='<div class="empty"><div class="empty-ico">🏋️</div><h3>No Drills Yet</h3><p>Create animated practice drills with players, cones, bags, balls, movement lines, notes, and video links.</p></div>';return;} el.innerHTML=st.items.map(d=>`<div class="card" onclick="openDrillEditor('${d.id}')"><div class="card-body"><div class="card-name">${esc(d.name)}</div><div class="card-sub">${esc(d.category||'Drill')} · ${(d.objects||[]).length} objects${d.videoUrl?' · Video':''}</div></div><button class="icon-del" onclick="event.stopPropagation();deleteDrill('${d.id}')">🗑</button><span class="chevron">›</span></div>`).join('');}
  window.openDrillsHome=proGuard(async()=>{ if(window.closeSheet) try{closeSheet('pbMenuSheet')}catch(e){} if(window.navTo) window.navTo('drillsScreen'); await load(); });
  window.newDrill=proGuard(async()=>{st.current={id:null,name:'New Drill',category:'',videoUrl:'',notes:''};st.objects=[];st.moves=[];openEditor();});
  window.openDrillEditor=proGuard(async(id)=>{const x=await api(),pb=x.currentPlaybook();const d=await x.getDoc(ref(x,pb.id,id));if(!d.exists()){toast('Drill not found','err');return;}st.current={id:d.id,...d.data()};st.objects=st.current.objects||[];st.moves=st.current.moves||st.current.movements||[];openEditor();});
  function openEditor(){document.getElementById('drillNameInput').value=st.current.name||'';document.getElementById('drillCategoryInput').value=st.current.category||'';document.getElementById('drillVideoInput').value=st.current.videoUrl||'';document.getElementById('drillNotesInput').value=st.current.notes||''; if(window.navTo) window.navTo('drillEditorScreen'); setTimeout(()=>{if(!st.canvas)bind(); resize();},60);}
  window.setDrillTool=(t)=>{st.tool=t;document.querySelectorAll('#drillEditorScreen .tool-btn').forEach(b=>b.classList.remove('on'));const b=document.getElementById('dr-'+t);if(b)b.classList.add('on');};
  window.saveDrill=proGuard(async()=>{const x=await api(),pb=x.currentPlaybook(); if(!pb)return; const data={name:document.getElementById('drillNameInput').value.trim()||'Untitled Drill',category:document.getElementById('drillCategoryInput').value.trim(),videoUrl:document.getElementById('drillVideoInput').value.trim(),notes:document.getElementById('drillNotesInput').value.trim(),objects:st.objects,moves:st.moves,updatedAt:Date.now()}; if(st.current&&st.current.id){await x.setDoc(ref(x,pb.id,st.current.id),data,{merge:true});} else {data.createdAt=Date.now();const d=await x.addDoc(col(x,pb.id),data);st.current={id:d.id,...data};} toast('Drill saved','ok'); await load();});
  window.deleteDrill=proGuard(async(id)=>{const x=await api(),pb=x.currentPlaybook(); if(!confirm('Delete this drill?'))return; await x.deleteDoc(ref(x,pb.id,id)); await load(); toast('Drill deleted','ok');});
  window.clearDrillBoard=()=>{if(confirm('Clear this drill board?')){st.objects=[];st.moves=[];st.selected=null;draw();}};
  window.animateDrill=()=>{st.anim=true;st.animStart=performance.now();draw();};
})();
