/* X&O Lab add-on: Pro Drills
   Additive only. Saves under playbooks/{playbookId}/drills and never touches live plays/formations. */
(function(){
  'use strict';
  const FW=1000,FH=600;
  const st={items:[],current:null,objects:[],animations:[],animIndex:0,tool:'select',selected:null,drawing:null,canvas:null,ctx:null,scale:1,offX:0,offY:0,playing:false,animStart:0};
  const wait=()=>new Promise(r=>setTimeout(r,50));
  async function api(){ for(let i=0;i<100;i++){ if(window.XOLab) return window.XOLab; await wait(); } throw new Error('X&O Lab core is not ready yet.'); }
  function esc(s){return String(s||'').replace(/[<>&"]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;'}[c]));}
  function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36);}
  function toast(m,t){(window.toast||alert)(m,t||'');}
  function proGuard(A){ return async function(){ const x=await api(); if(!x.isProRole()){ if(window.openProInfo) window.openProInfo(); else toast('Pro required','err'); return; } return A.apply(this,arguments); }; }
  function col(x,pbId){return x.collection(x.db,'playbooks',pbId,'drills');}
  function ref(x,pbId,id){return x.doc(x.db,'playbooks',pbId,'drills',id);}
  function moves(){ensureAnim(); return st.animations[st.animIndex].moves;}
  function ensureAnim(){if(!st.animations.length)st.animations=[{id:uid(),name:'Animation 1',moves:[]}]; if(!st.animations[st.animIndex])st.animIndex=0; if(!st.animations[st.animIndex].moves)st.animations[st.animIndex].moves=[];}
  function toS(x,y){const c=st.canvas;return {x:x*st.scale+st.offX+c.width/2-FW/2*st.scale,y:y*st.scale+st.offY+c.height/2-FH/2*st.scale};}
  function toF(x,y){const c=st.canvas;return {x:(x-st.offX-c.width/2+FW/2*st.scale)/st.scale,y:(y-st.offY-c.height/2+FH/2*st.scale)/st.scale};}
  function fit(){const c=st.canvas,p=18;st.scale=Math.min((c.width-p*2)/FW,(c.height-p*2)/FH);st.offX=0;st.offY=0;}
  function field(){const ctx=st.ctx,a=toS(0,0),b=toS(FW,FH),w=b.x-a.x,h=b.y-a.y;ctx.fillStyle='#173b14';ctx.fillRect(a.x,a.y,w,h);for(let i=0;i<10;i++){ctx.fillStyle=i%2?'#183f14':'#214d1b';ctx.fillRect(a.x,a.y+i*h/10,w,h/10);}ctx.strokeStyle='rgba(255,255,255,.28)';ctx.lineWidth=1.4;for(let i=0;i<=10;i++){let y=a.y+i*h/10;ctx.beginPath();ctx.moveTo(a.x,y);ctx.lineTo(b.x,y);ctx.stroke();}ctx.strokeStyle='rgba(255,255,255,.55)';ctx.strokeRect(a.x,a.y,w,h);}
  function movePoint(o){ if(!st.playing) return o; const m=moves().find(x=>x.objectId===o.id); if(!m||!m.points||m.points.length<2)return o; const total=1900,raw=Math.min(1,(performance.now()-st.animStart)/total); const eased=raw<.5?2*raw*raw:1-Math.pow(-2*raw+2,2)/2; const pts=m.points; const a=pts[0],b=pts[pts.length-1]; return {...o,x:a.x+(b.x-a.x)*eased,y:a.y+(b.y-a.y)*eased}; }
  function drawObj(raw){const o=movePoint(raw),ctx=st.ctx,s=toS(o.x,o.y);ctx.save();if(st.selected===raw){ctx.shadowColor='#fff';ctx.shadowBlur=14;} if(o.type==='cone'){ctx.fillStyle='#f97316';ctx.beginPath();ctx.moveTo(s.x,s.y-20);ctx.lineTo(s.x-16,s.y+15);ctx.lineTo(s.x+16,s.y+15);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(0,0,0,.65)';ctx.lineWidth=2;ctx.stroke();} else if(o.type==='bag'){ctx.fillStyle='#8b5e34';roundRect(ctx,s.x-24,s.y-13,48,26,7);ctx.fill();ctx.strokeStyle='rgba(0,0,0,.65)';ctx.stroke();} else if(o.type==='ball'){ctx.fillStyle='#8b4513';ctx.beginPath();ctx.ellipse(s.x,s.y,19,11,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.75)';ctx.beginPath();ctx.moveTo(s.x-8,s.y);ctx.lineTo(s.x+8,s.y);ctx.stroke();} else {ctx.fillStyle=o.color||'#f0b429';ctx.beginPath();ctx.arc(s.x,s.y,18,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(0,0,0,.8)';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#000';ctx.font='900 11px DM Sans';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText((o.label||'P').slice(0,3).toUpperCase(),s.x,s.y);}ctx.restore();}
  function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath();}
  function drawMove(m){if(!m.points||m.points.length<2)return;const ctx=st.ctx;ctx.strokeStyle='#41c97a';ctx.lineWidth=4;ctx.lineCap='round';ctx.setLineDash([12,8]);ctx.beginPath();m.points.forEach((p,i)=>{const s=toS(p.x,p.y);i?ctx.lineTo(s.x,s.y):ctx.moveTo(s.x,s.y);});ctx.stroke();ctx.setLineDash([]);const a=m.points[m.points.length-2],b=m.points[m.points.length-1],as=toS(a.x,a.y),bs=toS(b.x,b.y),ang=Math.atan2(bs.y-as.y,bs.x-as.x);ctx.beginPath();ctx.moveTo(bs.x,bs.y);ctx.lineTo(bs.x-Math.cos(ang-.55)*15,bs.y-Math.sin(ang-.55)*15);ctx.lineTo(bs.x-Math.cos(ang+.55)*15,bs.y-Math.sin(ang+.55)*15);ctx.closePath();ctx.fillStyle='#41c97a';ctx.fill();}
  function draw(){if(!st.canvas)return;ensureAnim();st.ctx.clearRect(0,0,st.canvas.width,st.canvas.height);field();moves().forEach(drawMove);st.objects.forEach(drawObj);updateHud();updateSelectedPanel(); if(st.playing){if(performance.now()-st.animStart<1950)requestAnimationFrame(draw);else{st.playing=false;draw();}}}
  function resize(){const w=document.getElementById('drillCanvasWrap'); if(!w||!st.canvas)return;st.canvas.width=w.offsetWidth;st.canvas.height=w.offsetHeight;fit();draw();}
  function hit(f){return st.objects.slice().reverse().find(o=>Math.hypot(o.x-f.x,o.y-f.y)<32/st.scale);}
  function ev(e){const r=st.canvas.getBoundingClientRect(),t=e.touches?e.touches[0]:e;return {x:t.clientX-r.left,y:t.clientY-r.top};}
  function bind(){st.canvas=document.getElementById('drillCanvas'); if(!st.canvas||st.canvas.dataset.bound)return; st.canvas.dataset.bound='1'; st.ctx=st.canvas.getContext('2d');resize();window.addEventListener('resize',resize);const down=e=>{e.preventDefault();ensureAnim();const s=ev(e),f=toF(s.x,s.y); if(['player','cone','bag','ball'].includes(st.tool)){const o={id:uid(),type:st.tool,label:st.tool==='player'?'P':'',x:Math.max(0,Math.min(FW,f.x)),y:Math.max(0,Math.min(FH,f.y)),color:'#f0b429'};st.objects.push(o);st.selected=o;draw();return;} if(st.tool==='move'){const h=hit(f); if(h){st.selected=h; st.drawing={objectId:h.id,points:[{x:h.x,y:h.y},f]}; st.animations[st.animIndex].moves=moves().filter(m=>m.objectId!==h.id); st.animations[st.animIndex].moves.push(st.drawing); draw();} return;} if(st.tool==='erase'){const h=hit(f); if(h){st.objects=st.objects.filter(o=>o!==h);st.animations.forEach(a=>a.moves=(a.moves||[]).filter(m=>m.objectId!==h.id));st.selected=null;draw();}else{st.animations[st.animIndex].moves.pop();draw();}return;} st.selected=hit(f);draw();};const move=e=>{if(!st.selected&&!st.drawing)return;e.preventDefault();const s=ev(e),f=toF(s.x,s.y); if(st.drawing){st.drawing.points=[st.drawing.points[0],f];draw();return;} if(st.selected){st.selected.x=Math.max(0,Math.min(FW,f.x));st.selected.y=Math.max(0,Math.min(FH,f.y));draw();}};const up=()=>{st.drawing=null;};['mousedown','touchstart'].forEach(n=>st.canvas.addEventListener(n,down,{passive:false}));['mousemove','touchmove'].forEach(n=>st.canvas.addEventListener(n,move,{passive:false}));['mouseup','mouseleave','touchend'].forEach(n=>st.canvas.addEventListener(n,up));}
  function miniSvg(d){const os=d.objects||[],an=(d.animations&&d.animations[0])||{moves:d.moves||d.movements||[]},ms=an.moves||[];let html=`<svg viewBox="0 0 1000 600" xmlns="http://www.w3.org/2000/svg"><rect width="1000" height="600" fill="#183f14"/>`;for(let i=0;i<=10;i++)html+=`<line x1="0" y1="${i*60}" x2="1000" y2="${i*60}" stroke="rgba(255,255,255,.22)" stroke-width="3"/>`;ms.slice(0,12).forEach(m=>{if(!m.points||m.points.length<2)return;html+=`<polyline points="${m.points.map(p=>`${p.x},${p.y}`).join(' ')}" fill="none" stroke="#41c97a" stroke-width="10" stroke-linecap="round" stroke-dasharray="24 14"/>`;});os.slice(0,28).forEach(o=>{if(o.type==='cone')html+=`<polygon points="${o.x},${o.y-26} ${o.x-20},${o.y+20} ${o.x+20},${o.y+20}" fill="#f97316"/>`;else if(o.type==='bag')html+=`<rect x="${o.x-28}" y="${o.y-15}" width="56" height="30" rx="8" fill="#8b5e34"/>`;else if(o.type==='ball')html+=`<ellipse cx="${o.x}" cy="${o.y}" rx="24" ry="15" fill="#8b4513"/>`;else html+=`<circle cx="${o.x}" cy="${o.y}" r="24" fill="#f0b429" stroke="#050505" stroke-width="5"/>`;});html+='</svg>';return 'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(html);}
  async function load(){const x=await api(),pb=x.currentPlaybook(); if(!pb)return; const snap=await x.getDocs(x.query(col(x,pb.id),x.orderBy('updatedAt'))); st.items=snap.docs.map(d=>({id:d.id,...d.data()})).reverse(); renderList();}
  function renderList(){const el=document.getElementById('drillsList'); if(!el)return; if(!st.items.length){el.innerHTML='<div class="empty"><div class="empty-ico">🏋️</div><h3>No Drills Yet</h3><p>Create animated practice drills with players, cones, bags, balls, movement lines, notes, and video links.</p></div>';return;} el.innerHTML='<div class="play-grid addon-grid">'+st.items.map(d=>{const ac=(d.animations&&d.animations.length)||1;return `<div class="play-card addon-play-card" onclick="openDrillEditor('${d.id}')"><div class="play-preview"><span class="img-tag play">Drill</span><img src="${miniSvg(d)}" alt=""></div><div class="play-card-name">${esc(d.name)}</div><div class="play-card-sub"><span>${esc(d.category||'Drill')} · ${ac} animation${ac===1?'':'s'}</span><button class="icon-del" onclick="event.stopPropagation();deleteDrill('${d.id}')">🗑</button></div></div>`;}).join('')+'</div>';}
  function updateHud(){const l=document.getElementById('drillAnimLabel'); if(l){ensureAnim();l.textContent=(st.animations[st.animIndex].name||`Animation ${st.animIndex+1}`)+` (${st.animIndex+1}/${st.animations.length})`;}}
  function updateSelectedPanel(){const box=document.getElementById('drillSelectedBox'),inp=document.getElementById('drillLabelInput'); if(!box||!inp)return; if(!st.selected){box.classList.add('muted');box.textContent='Tap an object to edit label';inp.value='';inp.disabled=true;return;} box.classList.remove('muted');box.textContent=st.selected.type==='player'?'Selected player label':`Selected ${st.selected.type}`;inp.disabled=st.selected.type!=='player';inp.value=st.selected.label||'';}
  window.updateDrillSelectedLabel=()=>{const inp=document.getElementById('drillLabelInput'); if(st.selected&&st.selected.type==='player'&&inp){st.selected.label=inp.value.toUpperCase().slice(0,3)||st.selected.label;draw();}};
  window.openDrillsHome=proGuard(async()=>{ if(window.closeSheet) try{closeSheet('pbMenuSheet')}catch(e){} if(window.navTo) window.navTo('drillsScreen'); await load(); });
  window.newDrill=proGuard(async()=>{st.current={id:null,name:'New Drill',category:'',videoUrl:'',notes:''};st.objects=[];st.animations=[{id:uid(),name:'Animation 1',moves:[]}];st.animIndex=0;openEditor();});
  window.openDrillEditor=proGuard(async(id)=>{const x=await api(),pb=x.currentPlaybook();const d=await x.getDoc(ref(x,pb.id,id));if(!d.exists()){toast('Drill not found','err');return;}st.current={id:d.id,...d.data()};st.objects=st.current.objects||[];st.animations=st.current.animations||[{id:uid(),name:'Animation 1',moves:st.current.moves||st.current.movements||[]}];st.animIndex=0;openEditor();});
  function openEditor(){document.getElementById('drillNameInput').value=st.current.name||'';document.getElementById('drillCategoryInput').value=st.current.category||'';document.getElementById('drillVideoInput').value=st.current.videoUrl||'';document.getElementById('drillNotesInput').value=st.current.notes||''; if(window.navTo) window.navTo('drillEditorScreen'); setTimeout(()=>{bind(); resize();},80);}
  window.setDrillTool=(t)=>{st.tool=t;document.querySelectorAll('#drillEditorScreen .tool-btn').forEach(b=>b.classList.remove('on'));const b=document.getElementById('dr-'+t);if(b)b.classList.add('on');};
  window.prevDrillAnimation=()=>{ensureAnim();st.animIndex=(st.animIndex-1+st.animations.length)%st.animations.length;draw();};
  window.nextDrillAnimation=()=>{ensureAnim();st.animIndex=(st.animIndex+1)%st.animations.length;draw();};
  window.addDrillAnimation=()=>{ensureAnim();st.animations.push({id:uid(),name:`Animation ${st.animations.length+1}`,moves:[]});st.animIndex=st.animations.length-1;draw();toast('Animation added','ok');};
  window.saveDrill=proGuard(async()=>{const x=await api(),pb=x.currentPlaybook(); if(!pb)return; ensureAnim(); const data={name:document.getElementById('drillNameInput').value.trim()||'Untitled Drill',category:document.getElementById('drillCategoryInput').value.trim(),videoUrl:document.getElementById('drillVideoInput').value.trim(),notes:document.getElementById('drillNotesInput').value.trim(),objects:st.objects,animations:st.animations,updatedAt:Date.now()}; if(st.current&&st.current.id){await x.setDoc(ref(x,pb.id,st.current.id),data,{merge:true});} else {data.createdAt=Date.now();const d=await x.addDoc(col(x,pb.id),data);st.current={id:d.id,...data};} toast('Drill saved','ok'); await load();});
  window.deleteDrill=proGuard(async(id)=>{const x=await api(),pb=x.currentPlaybook(); if(!confirm('Delete this drill?'))return; await x.deleteDoc(ref(x,pb.id,id)); await load(); toast('Drill deleted','ok');});
  window.clearDrillBoard=()=>{if(confirm('Clear this drill board?')){st.objects=[];st.animations=[{id:uid(),name:'Animation 1',moves:[]}];st.animIndex=0;st.selected=null;draw();}};
  window.animateDrill=()=>{ensureAnim();st.playing=true;st.animStart=performance.now();draw();};
})();
