/* X&O Lab add-on: Pro Sandbox
   Additive only. Saves under playbooks/{playbookId}/sandboxes and never touches live formations/plays. */
(function(){
  'use strict';
  const FW=1000,FH=600;
  const state={items:[],current:null,players:[],defenders:[],lines:[],tool:'select',selected:null,drawing:null,canvas:null,ctx:null,scale:1,offX:0,offY:0};
  const wait=()=>new Promise(r=>setTimeout(r,50));
  async function api(){ for(let i=0;i<100;i++){ if(window.XOLab) return window.XOLab; await wait(); } throw new Error('X&O Lab core is not ready yet.'); }
  function esc(s){return String(s||'').replace(/[<>&"]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;'}[c]));}
  function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36);}
  function toast(m,t){(window.toast||alert)(m,t||'');}
  function proGuard(A){ return async function(){ const x=await api(); if(!x.isProRole()){ if(window.openProInfo) window.openProInfo(); else toast('Pro required','err'); return; } return A.apply(this,arguments); }; }
  function col(x,pbId){return x.collection(x.db,'playbooks',pbId,'sandboxes');}
  function ref(x,pbId,id){return x.doc(x.db,'playbooks',pbId,'sandboxes',id);}
  function toS(x,y){const c=state.canvas;return {x:x*state.scale+state.offX+c.width/2-FW/2*state.scale,y:y*state.scale+state.offY+c.height/2-FH/2*state.scale};}
  function toF(x,y){const c=state.canvas;return {x:(x-state.offX-c.width/2+FW/2*state.scale)/state.scale,y:(y-state.offY-c.height/2+FH/2*state.scale)/state.scale};}
  function fit(){const c=state.canvas,p=18;state.scale=Math.min((c.width-p*2)/FW,(c.height-p*2)/FH);state.offX=0;state.offY=0;}
  function drawField(ctx){const a=toS(0,0),b=toS(FW,FH),w=b.x-a.x,h=b.y-a.y;ctx.fillStyle='#153b13';ctx.fillRect(a.x,a.y,w,h);for(let i=0;i<10;i++){ctx.fillStyle=i%2?'#183f14':'#214d1b';ctx.fillRect(a.x,a.y+i*h/10,w,h/10);}ctx.strokeStyle='rgba(255,255,255,.32)';ctx.lineWidth=1.4;for(let i=0;i<=10;i++){let y=a.y+i*h/10;ctx.beginPath();ctx.moveTo(a.x,y);ctx.lineTo(b.x,y);ctx.stroke();}let los=toS(0,FH/2).y;ctx.strokeStyle='#f0b429';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(a.x,los);ctx.lineTo(b.x,los);ctx.stroke();ctx.fillStyle='#f0b429';ctx.font='bold 12px DM Sans';ctx.textAlign='left';ctx.fillText('LOS',a.x+8,los-7);ctx.strokeStyle='rgba(255,255,255,.55)';ctx.strokeRect(a.x,a.y,w,h);}
  function drawPlayer(p,def){const ctx=state.ctx,s=toS(p.x,p.y),r=def?16:18;ctx.save();if(state.selected===p){ctx.shadowColor='#fff';ctx.shadowBlur=14;}ctx.beginPath();ctx.arc(s.x,s.y,r,0,Math.PI*2);ctx.fillStyle=def?'#f04141':(p.color||'#f0b429');ctx.fill();ctx.strokeStyle='rgba(0,0,0,.8)';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle=def?'#fff':'#000';ctx.font='900 11px DM Sans';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText((p.label||p.pos||'?').slice(0,3).toUpperCase(),s.x,s.y);ctx.restore();}
  function drawLine(l){const ctx=state.ctx;if(!l.points||l.points.length<2)return;ctx.strokeStyle=l.type==='block'?'#f0b429':'#41c97a';ctx.lineWidth=l.type==='block'?7:4;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();l.points.forEach((p,i)=>{const s=toS(p.x,p.y); i?ctx.lineTo(s.x,s.y):ctx.moveTo(s.x,s.y);});ctx.stroke();const end=l.points[l.points.length-1],prev=l.points[l.points.length-2];if(end&&prev&&l.type!=='block'){const a=toS(prev.x,prev.y),b=toS(end.x,end.y),ang=Math.atan2(b.y-a.y,b.x-a.x);ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-Math.cos(ang-.55)*15,b.y-Math.sin(ang-.55)*15);ctx.lineTo(b.x-Math.cos(ang+.55)*15,b.y-Math.sin(ang+.55)*15);ctx.closePath();ctx.fillStyle='#41c97a';ctx.fill();}}
  function draw(){const c=state.canvas;if(!c)return;state.ctx.clearRect(0,0,c.width,c.height);drawField(state.ctx);state.lines.forEach(drawLine);state.players.forEach(p=>drawPlayer(p,false));state.defenders.forEach(p=>drawPlayer(p,true));updateSelectedPanel();}
  function resize(){const wrap=document.getElementById('sandboxCanvasWrap'); if(!wrap||!state.canvas)return; state.canvas.width=wrap.offsetWidth; state.canvas.height=wrap.offsetHeight; fit(); draw();}
  function hit(pt){return [...state.players,...state.defenders].slice().reverse().find(p=>Math.hypot(p.x-pt.x,p.y-pt.y)<30/state.scale);}
  function getEvt(e){const r=state.canvas.getBoundingClientRect(); const t=e.touches?e.touches[0]:e; return {x:t.clientX-r.left,y:t.clientY-r.top};}
  function addPlayer(type,f){const p={id:uid(),type,label:type==='defense'?'D':'O',x:Math.max(0,Math.min(FW,f.x)),y:Math.max(0,Math.min(FH,f.y)),color:type==='defense'?'#f04141':'#f0b429'}; if(type==='defense')state.defenders.push(p); else state.players.push(p); state.selected=p; draw();}
  function bindCanvas(){state.canvas=document.getElementById('sandboxCanvas'); if(!state.canvas||state.canvas.dataset.bound)return; state.canvas.dataset.bound='1'; state.ctx=state.canvas.getContext('2d'); resize(); window.addEventListener('resize',resize); const down=e=>{e.preventDefault();const s=getEvt(e),f=toF(s.x,s.y); if(state.tool==='offense'||state.tool==='defense'){addPlayer(state.tool,f);return;} if(state.tool==='block'||state.tool==='route'){state.drawing={id:uid(),type:state.tool,points:[f]};state.lines.push(state.drawing);draw();return;} if(state.tool==='erase'){const h=hit(f); if(h){state.players=state.players.filter(p=>p!==h);state.defenders=state.defenders.filter(p=>p!==h);state.selected=null;draw();} else {state.lines.pop();draw();} return;} state.selected=hit(f); draw();}; const move=e=>{if(!state.selected&&!state.drawing)return; e.preventDefault();const s=getEvt(e),f=toF(s.x,s.y); if(state.drawing){const last=state.drawing.points[state.drawing.points.length-1]; if(!last||Math.hypot(last.x-f.x,last.y-f.y)>8)state.drawing.points.push(f);draw();return;} if(state.selected){state.selected.x=Math.max(0,Math.min(FW,f.x)); state.selected.y=Math.max(0,Math.min(FH,f.y)); draw();}}; const up=()=>{state.drawing=null;}; ['mousedown','touchstart'].forEach(n=>state.canvas.addEventListener(n,down,{passive:false})); ['mousemove','touchmove'].forEach(n=>state.canvas.addEventListener(n,move,{passive:false})); ['mouseup','mouseleave','touchend'].forEach(n=>state.canvas.addEventListener(n,up)); }
  function miniSvg(s){const ps=[...(s.players||s.offensePlayers||[]),...(s.defenders||s.defensePlayers||[])],ls=s.lines||[];let html=`<svg viewBox="0 0 1000 600" xmlns="http://www.w3.org/2000/svg"><rect width="1000" height="600" fill="#183f14"/>`;for(let i=0;i<=10;i++)html+=`<line x1="0" y1="${i*60}" x2="1000" y2="${i*60}" stroke="rgba(255,255,255,.22)" stroke-width="3"/>`;html+=`<line x1="0" y1="300" x2="1000" y2="300" stroke="#f0b429" stroke-width="8"/>`;ls.slice(0,12).forEach(l=>{if(!l.points||l.points.length<2)return;html+=`<polyline points="${l.points.map(p=>`${p.x},${p.y}`).join(' ')}" fill="none" stroke="${l.type==='block'?'#f0b429':'#41c97a'}" stroke-width="${l.type==='block'?14:9}" stroke-linecap="round" stroke-linejoin="round"/>`;});ps.slice(0,24).forEach(p=>{const def=(s.defenders||s.defensePlayers||[]).some(d=>d.id===p.id);html+=`<circle cx="${p.x}" cy="${p.y}" r="24" fill="${def?'#f04141':'#f0b429'}" stroke="#050505" stroke-width="5"/>`;});html+='</svg>';return 'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(html);}
  async function load(){const x=await api(),pb=x.currentPlaybook(); if(!pb)return; const snap=await x.getDocs(x.query(col(x,pb.id),x.orderBy('updatedAt'))); state.items=snap.docs.map(d=>({id:d.id,...d.data()})).reverse(); renderList();}
  function renderList(){const el=document.getElementById('sandboxList'); if(!el)return; if(!state.items.length){el.innerHTML='<div class="empty"><div class="empty-ico">🧪</div><h3>No Sandbox Work Yet</h3><p>Create a temporary board for fronts, blocking schemes, and play tweaks. It will not edit live plays.</p></div>';return;} el.innerHTML='<div class="play-grid addon-grid">'+state.items.map(s=>`<div class="play-card addon-play-card" onclick="openSandboxEditor('${s.id}')"><div class="play-preview"><span class="img-tag play">Sandbox</span><img src="${miniSvg(s)}" alt=""></div><div class="play-card-name">${esc(s.name)}</div><div class="play-card-sub"><span>${(s.defenders||s.defensePlayers||[]).length} DEF · ${(s.lines||[]).length} marks</span><button class="icon-del" onclick="event.stopPropagation();deleteSandbox('${s.id}')">🗑</button></div></div>`).join('')+'</div>';}
  function updateSelectedPanel(){const box=document.getElementById('sandboxSelectedBox'),inp=document.getElementById('sandboxLabelInput'); if(!box||!inp)return; if(!state.selected){box.classList.add('muted');box.textContent='Tap a player to edit label';inp.value='';inp.disabled=true;return;} box.classList.remove('muted');box.textContent='Selected player label';inp.disabled=false;inp.value=state.selected.label||'';}
  window.updateSandboxSelectedLabel=()=>{const inp=document.getElementById('sandboxLabelInput'); if(state.selected&&inp){state.selected.label=inp.value.toUpperCase().slice(0,3)||state.selected.label;draw();}};
  window.openSandboxHome=proGuard(async()=>{ if(window.closeSheet) try{closeSheet('pbMenuSheet')}catch(e){} if(window.navTo) window.navTo('sandboxScreen'); await load(); });
  window.newSandbox=proGuard(async()=>{ state.current={id:null,name:'New Sandbox',notes:''}; state.players=[]; state.defenders=[]; state.lines=[]; openEditor(); });
  window.openSandboxEditor=proGuard(async(id)=>{const x=await api(),pb=x.currentPlaybook(); const d=await x.getDoc(ref(x,pb.id,id)); if(!d.exists()){toast('Sandbox not found','err');return;} state.current={id:d.id,...d.data()}; state.players=state.current.players||state.current.offensePlayers||[]; state.defenders=state.current.defenders||state.current.defensePlayers||[]; state.lines=state.current.lines||[]; openEditor();});
  function openEditor(){document.getElementById('sandboxNameInput').value=state.current.name||'';document.getElementById('sandboxNotesInput').value=state.current.notes||''; if(window.navTo) window.navTo('sandboxEditorScreen'); setTimeout(()=>{bindCanvas(); resize();},80);}
  window.setSandboxTool=(t)=>{state.tool=t; document.querySelectorAll('#sandboxEditorScreen .tool-btn').forEach(b=>b.classList.remove('on')); const b=document.getElementById('sb-'+t); if(b)b.classList.add('on');};
  window.saveSandbox=proGuard(async()=>{const x=await api(),pb=x.currentPlaybook(); if(!pb)return; const data={name:document.getElementById('sandboxNameInput').value.trim()||'Untitled Sandbox',notes:document.getElementById('sandboxNotesInput').value.trim(),players:state.players,defenders:state.defenders,lines:state.lines,updatedAt:Date.now()}; if(state.current&&state.current.id){await x.setDoc(ref(x,pb.id,state.current.id),data,{merge:true});} else {data.createdAt=Date.now(); const d=await x.addDoc(col(x,pb.id),data); state.current={id:d.id,...data};} toast('Sandbox saved','ok'); await load();});
  window.deleteSandbox=proGuard(async(id)=>{const x=await api(),pb=x.currentPlaybook(); if(!confirm('Delete this sandbox?'))return; await x.deleteDoc(ref(x,pb.id,id)); await load(); toast('Sandbox deleted','ok');});
  window.clearSandboxBoard=()=>{if(confirm('Clear this sandbox board?')){state.players=[];state.defenders=[];state.lines=[];state.selected=null;draw();}};
})();
