/* X&O Lab add-on: Pro Sandbox
   Additive only. Saves under playbooks/{playbookId}/sandboxes and never touches live formations/plays. */
(function(){
  'use strict';
  const FW=1000,FH=600;
  const state={items:[],current:null,players:[],defenders:[],lines:[],tool:'select',selected:null,drawing:null,canvas:null,ctx:null,scale:1,offX:0,offY:0};
  const wait=()=>new Promise(r=>setTimeout(r,50));
  async function api(){ for(let i=0;i<80;i++){ if(window.XOLab) return window.XOLab; await wait(); } throw new Error('X&O Lab core is not ready yet.'); }
  function esc(s){return String(s||'').replace(/[<>&"]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;'}[c]));}
  function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36);}
  function toast(m,t){(window.toast||alert)(m,t||'');}
  function proGuard(A){ return async function(){ const x=await api(); if(!x.isProRole()){ if(window.openProInfo) window.openProInfo(); else toast('Pro required','err'); return; } return A.apply(this,arguments); }; }
  function col(x,pbId){return x.collection(x.db,'playbooks',pbId,'sandboxes');}
  function ref(x,pbId,id){return x.doc(x.db,'playbooks',pbId,'sandboxes',id);}
  function toS(x,y){const c=state.canvas;return {x:x*state.scale+state.offX+c.width/2-FW/2*state.scale,y:y*state.scale+state.offY+c.height/2-FH/2*state.scale};}
  function toF(x,y){const c=state.canvas;return {x:(x-state.offX-c.width/2+FW/2*state.scale)/state.scale,y:(y-state.offY-c.height/2+FH/2*state.scale)/state.scale};}
  function fit(){const c=state.canvas, pad=18; state.scale=Math.min((c.width-pad*2)/FW,(c.height-pad*2)/FH); state.offX=0; state.offY=0;}
  function drawField(ctx){const a=toS(0,0),b=toS(FW,FH),w=b.x-a.x,h=b.y-a.y;ctx.fillStyle='#1e4d18';ctx.fillRect(a.x,a.y,w,h);for(let i=0;i<10;i++){ctx.fillStyle=i%2?'#1a4516':'#234f1c';ctx.fillRect(a.x,a.y+i*h/10,w,h/10);}ctx.strokeStyle='rgba(255,255,255,.35)';ctx.lineWidth=1.5;for(let i=0;i<=10;i++){let y=a.y+i*h/10;ctx.beginPath();ctx.moveTo(a.x,y);ctx.lineTo(b.x,y);ctx.stroke();}let los=toS(0,FH/2).y;ctx.strokeStyle='#f0b429';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(a.x,los);ctx.lineTo(b.x,los);ctx.stroke();ctx.fillStyle='#f0b429';ctx.font='bold 12px DM Sans';ctx.fillText('LOS',a.x+8,los-5);ctx.strokeStyle='rgba(255,255,255,.55)';ctx.strokeRect(a.x,a.y,w,h);}
  function drawPlayer(p,def){const ctx=state.ctx,s=toS(p.x,p.y),r=def?16:18;ctx.save();if(state.selected===p){ctx.shadowColor='#fff';ctx.shadowBlur=12;}ctx.beginPath();ctx.arc(s.x,s.y,r,0,Math.PI*2);ctx.fillStyle=def?'#f04141':(p.color||'#f0b429');ctx.fill();ctx.strokeStyle='#111';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle=def?'#fff':'#000';ctx.font='bold 11px DM Sans';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText((p.label||p.pos||'?').slice(0,3),s.x,s.y);ctx.restore();}
  function drawLine(l){const ctx=state.ctx;if(!l.points||l.points.length<2)return;ctx.strokeStyle=l.type==='block'?'#f0b429':'#41c97a';ctx.lineWidth=l.type==='block'?7:4;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();l.points.forEach((p,i)=>{const s=toS(p.x,p.y); i?ctx.lineTo(s.x,s.y):ctx.moveTo(s.x,s.y);});ctx.stroke();}
  function draw(){const c=state.canvas;if(!c)return;state.ctx.clearRect(0,0,c.width,c.height);drawField(state.ctx);state.lines.forEach(drawLine);state.players.forEach(p=>drawPlayer(p,false));state.defenders.forEach(p=>drawPlayer(p,true));}
  function resize(){const wrap=document.getElementById('sandboxCanvasWrap'); if(!wrap||!state.canvas)return; state.canvas.width=wrap.offsetWidth; state.canvas.height=wrap.offsetHeight; fit(); draw();}
  function hit(pt){return [...state.players,...state.defenders].find(p=>Math.hypot(p.x-pt.x,p.y-pt.y)<28/state.scale);}
  function getEvt(e){const r=state.canvas.getBoundingClientRect(); const t=e.touches?e.touches[0]:e; return {x:t.clientX-r.left,y:t.clientY-r.top};}
  function bindCanvas(){state.canvas=document.getElementById('sandboxCanvas'); state.ctx=state.canvas.getContext('2d'); resize(); window.addEventListener('resize',resize); const down=e=>{e.preventDefault();const s=getEvt(e),f=toF(s.x,s.y); if(state.tool==='offense'){state.players.push({id:uid(),pos:'O',label:'O',x:f.x,y:f.y,color:'#f0b429'});state.selected=state.players[state.players.length-1];draw();return;} if(state.tool==='defense'){state.defenders.push({id:uid(),label:'D',x:f.x,y:f.y});state.selected=state.defenders[state.defenders.length-1];draw();return;} if(state.tool==='block'||state.tool==='route'){state.drawing={id:uid(),type:state.tool,points:[f]};state.lines.push(state.drawing);draw();return;} if(state.tool==='erase'){const h=hit(f); if(h){state.players=state.players.filter(p=>p!==h);state.defenders=state.defenders.filter(p=>p!==h);state.selected=null;draw();} return;} state.selected=hit(f); draw();}; const move=e=>{if(!state.selected&&!state.drawing)return; e.preventDefault();const s=getEvt(e),f=toF(s.x,s.y); if(state.drawing){state.drawing.points.push(f);draw();return;} if(state.selected){state.selected.x=Math.max(0,Math.min(FW,f.x)); state.selected.y=Math.max(0,Math.min(FH,f.y)); draw();}}; const up=()=>{state.drawing=null;}; ['mousedown','touchstart'].forEach(n=>state.canvas.addEventListener(n,down,{passive:false})); ['mousemove','touchmove'].forEach(n=>state.canvas.addEventListener(n,move,{passive:false})); ['mouseup','mouseleave','touchend'].forEach(n=>state.canvas.addEventListener(n,up)); }
  async function load(){const x=await api(),pb=x.currentPlaybook(); if(!pb)return; const snap=await x.getDocs(x.query(col(x,pb.id),x.orderBy('updatedAt'))); state.items=snap.docs.map(d=>({id:d.id,...d.data()})).reverse(); renderList();}
  function renderList(){const el=document.getElementById('sandboxList'); if(!el)return; if(!state.items.length){el.innerHTML='<div class="empty"><div class="empty-ico">🧪</div><h3>No Sandbox Work Yet</h3><p>Create a temporary board for fronts, blocking schemes, and play tweaks. It will not edit live plays.</p></div>';return;} el.innerHTML=state.items.map(s=>`<div class="card" onclick="openSandboxEditor('${s.id}')"><div class="card-body"><div class="card-name">${esc(s.name)}</div><div class="card-sub">${esc(s.notes||'Temporary sandbox board')} · ${((s.defenders||[]).length)} defenders</div></div><button class="icon-del" onclick="event.stopPropagation();deleteSandbox('${s.id}')">🗑</button><span class="chevron">›</span></div>`).join('');}
  window.openSandboxHome=proGuard(async()=>{ if(window.closeSheet) try{closeSheet('pbMenuSheet')}catch(e){} if(window.navTo) window.navTo('sandboxScreen'); await load(); });
  window.newSandbox=proGuard(async()=>{ state.current={id:null,name:'New Sandbox',notes:''}; state.players=[]; state.defenders=[]; state.lines=[]; openEditor(); });
  window.openSandboxEditor=proGuard(async(id)=>{const x=await api(),pb=x.currentPlaybook(); const d=await x.getDoc(ref(x,pb.id,id)); if(!d.exists()){toast('Sandbox not found','err');return;} state.current={id:d.id,...d.data()}; state.players=state.current.players||state.current.offensePlayers||[]; state.defenders=state.current.defenders||state.current.defensePlayers||[]; state.lines=state.current.lines||[]; openEditor();});
  function openEditor(){document.getElementById('sandboxNameInput').value=state.current.name||'';document.getElementById('sandboxNotesInput').value=state.current.notes||''; if(window.navTo) window.navTo('sandboxEditorScreen'); setTimeout(()=>{if(!state.canvas)bindCanvas(); resize();},60);}
  window.setSandboxTool=(t)=>{state.tool=t; document.querySelectorAll('#sandboxEditorScreen .tool-btn').forEach(b=>b.classList.remove('on')); const b=document.getElementById('sb-'+t); if(b)b.classList.add('on');};
  window.saveSandbox=proGuard(async()=>{const x=await api(),pb=x.currentPlaybook(); if(!pb)return; const data={name:document.getElementById('sandboxNameInput').value.trim()||'Untitled Sandbox',notes:document.getElementById('sandboxNotesInput').value.trim(),players:state.players,defenders:state.defenders,lines:state.lines,updatedAt:Date.now()}; if(state.current&&state.current.id){await x.setDoc(ref(x,pb.id,state.current.id),data,{merge:true});} else {data.createdAt=Date.now(); const d=await x.addDoc(col(x,pb.id),data); state.current={id:d.id,...data};} toast('Sandbox saved','ok'); await load();});
  window.deleteSandbox=proGuard(async(id)=>{const x=await api(),pb=x.currentPlaybook(); if(!confirm('Delete this sandbox?'))return; await x.deleteDoc(ref(x,pb.id,id)); await load(); toast('Sandbox deleted','ok');});
  window.clearSandboxBoard=()=>{if(confirm('Clear this sandbox board?')){state.players=[];state.defenders=[];state.lines=[];state.selected=null;draw();}};
})();
