export function emptyLine(p){return {id:p.id,num:p.num,name:p.name,snaps:0,off:0,def:0,st:0,rushAtt:0,rushYds:0,rushTd:0,rec:0,recYds:0,recTd:0,passAtt:0,passCmp:0,passYds:0,passTd:0,intsThrown:0,tackles:0,assists:0,sacks:0,ints:0,ff:0,fr:0,tdAllowed:0,longRush:0,longRec:0,games:0};}
export function gameStats(game, roster=[]){const map={}; roster.forEach(p=>map[p.id]=emptyLine(p)); const team={snaps:0,off:0,def:0,st:0,rushAtt:0,rushYds:0,passAtt:0,passCmp:0,passYds:0,rec:0,recYds:0,tackles:0,assists:0,sacks:0,ints:0,fr:0,td:0};
(game.plays||[]).forEach(pl=>{team.snaps++; if(pl.phase==='offense')team.off++; else if(pl.phase==='defense')team.def++; else team.st++; (pl.players||[]).forEach(id=>{if(map[id]){map[id].snaps++; if(pl.phase==='offense')map[id].off++; else if(pl.phase==='defense')map[id].def++; else map[id].st++;}}); const y=Number(pl.yards||0);
 if(pl.type==='run'&&pl.primary){const a=map[pl.primary]; if(a){a.rushAtt++;a.rushYds+=y;a.longRush=Math.max(a.longRush,y);if(pl.result==='td')a.rushTd++;} team.rushAtt++;team.rushYds+=y;if(pl.result==='td')team.td++;}
 if(pl.type==='pass'){team.passAtt++; const passer=map[pl.primary]; if(passer)passer.passAtt++; if(pl.result==='complete'||pl.result==='td'){team.passCmp++;team.passYds+=y;team.rec++;team.recYds+=y;if(passer){passer.passCmp++;passer.passYds+=y;} const r=map[pl.receiver]; if(r){r.rec++;r.recYds+=y;r.longRec=Math.max(r.longRec,y);} } if(pl.result==='td'){team.td++; if(passer)passer.passTd++; const r=map[pl.receiver]; if(r)r.recTd++;} if(pl.result==='int'&&passer)passer.intsThrown++;}
 if(pl.tackler&&map[pl.tackler]){map[pl.tackler].tackles++;team.tackles++;} if(pl.assist&&map[pl.assist]){map[pl.assist].assists++;team.assists++;} if(pl.defResult==='sack'&&pl.tackler&&map[pl.tackler]){map[pl.tackler].sacks++;team.sacks++;} if(pl.defResult==='int'&&pl.tackler&&map[pl.tackler]){map[pl.tackler].ints++;team.ints++;} if(pl.defResult==='fumble'&&pl.tackler&&map[pl.tackler]){map[pl.tackler].fr++;team.fr++;} if(pl.defResult==='tdAllowed'&&pl.tackler&&map[pl.tackler])map[pl.tackler].tdAllowed++; });
 return {team,players:Object.values(map).sort((a,b)=>b.snaps-a.snaps||Number(a.num)-Number(b.num))};}
export function seasonStats(games, roster=[]){const base={}; roster.forEach(p=>base[p.id]=emptyLine(p)); const team={games:0,snaps:0,off:0,def:0,st:0,rushAtt:0,rushYds:0,passAtt:0,passCmp:0,passYds:0,rec:0,recYds:0,tackles:0,assists:0,sacks:0,ints:0,fr:0,td:0}; const gameLogs={};
 games.filter(g=>g.status==='ended').forEach(g=>{team.games++; const gs=gameStats(g,roster); Object.keys(team).forEach(k=>{if(k!=='games')team[k]+=gs.team[k]||0}); gs.players.forEach(line=>{if(!base[line.id])base[line.id]=emptyLine(line); const had=line.snaps>0; Object.keys(line).forEach(k=>{if(typeof line[k]==='number'&&k!=='games')base[line.id][k]+=line[k];}); if(had)base[line.id].games++; (gameLogs[line.id] ||= []).push({game:g.name||g.opponent,date:g.date,team:g.team,stats:line});});});
 return {team,players:Object.values(base).sort((a,b)=>b.snaps-a.snaps||Number(a.num)-Number(b.num)),gameLogs};}
export function csv(rows){return rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');}
export function download(name,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);}
export function boxscoreHtml(game, roster){const s=gameStats(game,roster); const rows=(arr,cols)=>`<table class="table"><thead><tr>${cols.map(c=>`<th>${c[0]}</th>`).join('')}</tr></thead><tbody>${arr.map(p=>`<tr>${cols.map(c=>`<td>${c[1](p)}</td>`).join('')}</tr>`).join('')}</tbody></table>`; const off=s.players.filter(p=>p.off||p.rushAtt||p.rec||p.passAtt); const def=s.players.filter(p=>p.def||p.tackles||p.assists||p.sacks||p.ints||p.fr); const part=s.players.filter(p=>p.snaps);
 return `<div class="score-grid"><div class="metric blue"><b>${s.team.snaps}</b><span>Total Snaps</span></div><div class="metric green"><b>${s.team.rushYds+s.team.passYds}</b><span>Off Yards</span></div><div class="metric amber"><b>${s.team.tackles+s.team.assists}</b><span>Tackles</span></div></div><h3>Offense</h3>${rows(off,[['Player',p=>`#${p.num} ${p.name}`],['Off',p=>p.off],['Rush',p=>`${p.rushAtt}-${p.rushYds}`],['Long',p=>p.longRush],['Rec',p=>`${p.rec}-${p.recYds}`],['TD',p=>p.rushTd+p.recTd]])}<h3>Defense</h3>${rows(def,[['Player',p=>`#${p.num} ${p.name}`],['Def',p=>p.def],['Tkl',p=>p.tackles],['Ast',p=>p.assists],['Sack',p=>p.sacks],['INT',p=>p.ints],['FR',p=>p.fr]])}<h3>Participation</h3>${rows(part,[['Player',p=>`#${p.num} ${p.name}`],['Snaps',p=>p.snaps],['Off',p=>p.off],['Def',p=>p.def],['ST',p=>p.st],['%',p=>s.team.snaps?Math.round(p.snaps/s.team.snaps*100)+'%':'0%']])}`;}
export function gameCsv(game,roster){const s=gameStats(game,roster); return csv([['Player','Snaps','Off','Def','ST','RushAtt','RushYds','Rec','RecYds','Tackles','Assists','Sacks','INT','FR'],...s.players.map(p=>[`${p.num} ${p.name}`,p.snaps,p.off,p.def,p.st,p.rushAtt,p.rushYds,p.rec,p.recYds,p.tackles,p.assists,p.sacks,p.ints,p.fr])]);}
export function seasonCsv(games,roster){const s=seasonStats(games,roster); return csv([['Player','Games','Snaps','Off','Def','ST','RushAtt','RushYds','Rec','RecYds','Tackles','Assists','Sacks','INT','FR'],...s.players.map(p=>[`${p.num} ${p.name}`,p.games,p.snaps,p.off,p.def,p.st,p.rushAtt,p.rushYds,p.rec,p.recYds,p.tackles,p.assists,p.sacks,p.ints,p.fr])]);}
